jobportal/jobportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobportal/jobs/urls.py
from django.urls import path, include

from .views import *

app_name= 'jobs'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('create-job', CreateJobView.as_view(), name='create_job'),

]

jobportal/jobs/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField

from jobportal import settings

JOB_TYPES_OPTIONS = (
('full_time', _('Full time')),
('part_time', _('Part time')),
('freelance', _('Freelance')),
('internship', _('Internship')),
('temporary', _('Temporary')),
)

class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(default=None, editable=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def job_count(self):
        return self.jobs.all().count()

class Job(models.Model):
    title = models.CharField(max_length=300)
    company = models.CharField(max_length=300)
    type = models.CharField(max_length=20, blank=False, default=None, choices=JOB_TYPES_OPTIONS)
    location = models.CharField(max_length=50, blank=False, default=None)
    description = RichTextField(blank=False, default=None)
    publishing_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(default=None, editable=False)
    employer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='jobs')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Job, self).save(*args, **kwargs)

    class Meta:
        ordering = ('-id', )

jobportal/jobs/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView, DetailView
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import method_decorator, login_required

from .models import Job, Category
from .forms import CreateJobForm

class HomeView(ListView):
    model = Job
    template_name = 'jobs/index.html'
    context_object_name = 'jobs'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

@method_decorator(login_required(login_url='/'), name='dispatch')
class CreateJobView(SuccessMessageMixin, CreateView):
    model = Job
    template_name = 'jobs/create-job.html'
    form_class = CreateJobForm
    success_url = '/'
    success_message = _('Job has been created')

    def valid_form(self, form):
        job = form.save(commit=False)
        job.employer = self.request.user
        job.save()
        return super(CreateJobView, self).form_valid(form)


class SingleJobView(DetailView):
    model = Job
    template_name = 'jobs/single.html'
    context_object_name = 'job'

jobportal/templates/jobs/partials/_categoriesheading.html
<div class="row justify-content-center mb-5 pb-3">
  <div class="col-md-7 heading-section text-center ftco-animate">
    <span class="subheading">Categories work wating for you</span>
    <h2 class="mb-4"><span>Current</span> Job Posts</h2>
  </div>
</div>

jobportal/templates/jobs/partials/_categorylist.html
<div class="row">
    {% for category in categories %}
  <div class="col-md-3 ftco-animate">
    <ul class="category">
      <li><a href="#">{{ category.title }} <span class="number" data-number="{{ category.job_count }}">0</span></a></li>
    </ul>
  </div>
    {% endfor %}
</div>

jobportal/templates/jobs/partials/_joblist.html
<div class="row">
{% for job in jobs %}
<div class="col-md-12 ftco-animate">
  <div class="job-post-item bg-white p-4 d-block d-md-flex align-items-center">

    <div class="mb-4 mb-md-0 mr-5">
     <div class="job-post-item-header d-flex align-items-center">
       <h2 class="mr-3 text-black h4">{{ job.title }}</h2>
        <div class="badge-wrap">
            <span {% if job.type == 'full_time' %}
                    class="bg-warning text-white badge py-2 px-3"

                  {% elif job.type == 'part_time' %}
                    class="bg-info text-white badge py-2 px-3"

                  {% elif job.type == 'freelance' %}
                    class="bg-secondary text-white badge py-2 px-3"

                  {% elif job.type == 'internship' %}
                    class="bg-primary text-white badge py-2 px-3"

                  {% elif job.type == 'temporary' %}
                    class="bg-danger text-white badge py-2 px-3"
                  {% endif %}> {{ job.get_type_display }}
            </span>
       </div>
     </div>
     <div class="job-post-item-body d-block d-md-flex">
       <div class="mr-3"><span class="icon-layers"></span> <a href="#">{{ job.company }}</a></div>
       <div><span class="icon-my_location"></span> <span>{{ job.location }}</span></div>
     </div>
    </div>

    <div class="ml-auto d-flex">
      <a href="#" class="btn btn-primary py-2 mr-1">Apply Job</a>
        {% if job.id in wish_list %}
          <a href="javascripts:void(0);"
            id="jobwl{{ job.id }}"
            title="Remove from my wish list"
            data-wl="1"
            onclick="addorremove({{ job.id }})"
            class="btn btn-danger rounded-circle btn-favorite d-flex align-items-center">
            <span class="icon-heart"></span>
          </a>
        {% else %}
          <a href="javascripts:void(0);"
            id="jobwl{{ job.id }}"
            title="Add to my wish list"
            data-wl="0"
            onclick="addorremove({{ job.id }})"
            class="btn btn-primary rounded-circle btn-favorite d-flex align-items-center">
            <span class="icon-heart"></span>
          </a>
        {% endif %}
    </div>
  </div>
</div> <!-- end -->
{% endfor %}
 </div>

jobportal/templates/jobs/partials/_pagination.html
<div class="row mt-5">
{% if is_paginated %}
  <div class="col text-center">
    <div class="block-27">
      <ul>
          <!-- previous page -->
          {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
          {% else %}
            <li class="disabled"><span>&lt;</span></li>
          {% endif %}

          <!-- pages in between -->
          {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="active"><span>{{ i }}</span></li>
            {% else %}
              <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}

          <!-- next page -->
          {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
          {% else %}
            <li class="disabled"><span>&gt;</span></li>
          {% endif %}
      </ul>
    </div>
  </div>
{% endif %}
</div>

jobportal/templates/jobs/partials/_recentjobsheading.html
<div class="row justify-content-center mb-5 pb-3">
  <div class="col-md-7 heading-section text-center ftco-animate">
    <span class="subheading">Recently Added Jobs</span>
    <h2 class="mb-4"><span>Recent</span> Jobs</h2>
  </div>
</div>