jobportal/jobportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobportal/jobs/urls.py
from django.urls import path, include

from .views import *

app_name= 'jobs'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('create-job', CreateJobView.as_view(), name='create_job'),

]

jobportal/users/urls.py
from django.urls import path, include

from .views import *

app_name= 'users'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('update-profile/<int:pk>/', UserUpdateView.as_view(), name='update_profile'),
]

jobportal/templates/partials/_footer.html
<footer class="ftco-footer ftco-bg-dark ftco-section">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md">
         <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">About</h2>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Employers</h2>
          <ul class="list-unstyled">
            <li><a href="#" class="py-2 d-block">How it works</a></li>
            <li><a href="#" class="py-2 d-block">Register</a></li>
            <li><a href="#" class="py-2 d-block">Post a Job</a></li>
            <li><a href="#" class="py-2 d-block">Advance Skill Search</a></li>
            <li><a href="#" class="py-2 d-block">Recruiting Service</a></li>
            <li><a href="#" class="py-2 d-block">Blog</a></li>
            <li><a href="#" class="py-2 d-block">Faq</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4 ml-md-4">
          <h2 class="ftco-heading-2">Workers</h2>
          <ul class="list-unstyled">
            <li><a href="#" class="py-2 d-block">How it works</a></li>
            <li><a href="#" class="py-2 d-block">Register</a></li>
            <li><a href="#" class="py-2 d-block">Post Your Skills</a></li>
            <li><a href="#" class="py-2 d-block">Job Search</a></li>
            <li><a href="#" class="py-2 d-block">Emploer Search</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Have a Questions?</h2>
          <div class="block-23 mb-3">
            <ul>
              <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
              <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
              <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">

        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
      </div>
    </div>
  </div>
</footer>

jobportal/templates/partials/_head.html
{% load static %}

<title>JobPortal - Free Bootstrap 4 Template by Colorlib</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">

<link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
<link rel="stylesheet" href="{% static "css/animate.css" %}">

<link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
<link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
<link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">

<link rel="stylesheet" href="{% static "css/aos.css" %}">

<link rel="stylesheet" href="{% static "css/ionicons.min.css" %}">

<link rel="stylesheet" href="{% static "css/bootstrap-datepicker.css" %}">
<link rel="stylesheet" href="{% static "css/jquery.timepicker.css" %}">


<link rel="stylesheet" href="{% static "css/flaticon.css" %}">
<link rel="stylesheet" href="{% static "css/icomoon.css" %}">
<link rel="stylesheet" href="{% static "css/style.css" %}">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

jobportal/templates/partials/_loader.html
<div id="ftco-loader" class="show fullscreen">
  <svg class="circular" width="48px" height="48px">
    <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
    <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/>
</svg>
</div>

jobportal/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <a class="navbar-brand" href="{% url 'jobs:home' %}">JobPortal</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> Menu
    </button>

    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active"><a href="{% url 'jobs:home' %}" class="nav-link">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Blog</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Contact</a></li>
            {% if not user.is_authenticated %}
        <li class="nav-item cta mr-md-2"><a href="{% url 'users:register' %}" class="nav-link">Register</a></li>
        <li class="nav-item cta cta-colored"><a href="{% url 'users:login' %}" class="nav-link">Login</a></li>
            {% endif %}
            {% if user.is_authenticated and user.is_employee %}
            <div class="btn-group">
              <button type="button" class="btn btn-success dropdown-toggle" style="height:50px" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      {{ user.first_name }}
              </button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">My Jobs</a>
                <a class="dropdown-item" href="{% url 'users:employee_messages' pk=user.pk %}">You Have {{ user.count_unread_messages }} message(s)</a>
                <a class="dropdown-item" href="{% url 'users:my_wish_list' pk=user.id %}">My Wish List</a>
                <a class="dropdown-item" href="{% url 'users:update_profile' pk=user.get_profile_id %}">Update Profile</a>
                <a class="dropdown-item" href="{% url 'users:password_change' %}">Change Password</a>
                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
              </div>
            </div>
            {% endif %}
            {% if user.is_authenticated and user.is_employer %}
            <div class="btn-group">
              <button type="button" class="btn btn-success dropdown-toggle" style="height:50px" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.first_name }}
              </button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'jobs:create_job' %}">Add Job</a>
                <a class="dropdown-item" href="{% url 'users:employer_jobs' %}">My Jobs</a>
                {% if user.get_profile_id %}
                  <a class="dropdown-item" href="{% url 'users:update_profile' pk=user.get_profile_id %}">Update Profile</a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'users:password_change' %}">Change Password</a>
                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
              </div>
            </div>
            {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- END nav -->

jobportal/templates/partials/_scripts.html
{% load static %}


<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/jquery-migrate-3.0.1.min.js" %}"></script>
<script src="{% static "js/popper.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/jquery.easing.1.3.js" %}"></script>
<script src="{% static "js/jquery.waypoints.min.js" %}"></script>
<script src="{% static "js/jquery.stellar.min.js" %}"></script>
<script src="{% static "js/owl.carousel.min.js" %}"></script>
<script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "js/aos.js" %}"></script>
<script src="{% static "js/jquery.animateNumber.min.js" %}"></script>
<script src="{% static "js/bootstrap-datepicker.js" %}"></script>
<script src="{% static "js/jquery.timepicker.min.js" %}"></script>
<script src="{% static "js/scrollax.min.js" %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static "js/google-map.js" %}"></script>
<script src="{% static "js/main.js" %}"></script>
{% if user.is_authenticated and user.is_employee %}
    <script src="{% static "js/addorremove.js" %}"></script>
    {% else %}
    <script src="{% static "js/addorremove2.js" %}"></script>
{% endif %}

jobportal/templates/partials/_subscribesection.html
<section class="ftco-section-parallax">
<div class="parallax-img d-flex align-items-center">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
        <h2>Subcribe to our Newsletter</h2>
        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>
        <div class="row d-flex justify-content-center mt-4 mb-4">
          <div class="col-md-8">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>